pagarme/magento2

.circleci/config.yml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-83
| **What?**         | Fixes "composer" on CircleCI's script
| **How?**          | Removing self-update from script
=> [Bugfix] Fixes "composer" on CircleCI's script

view/adminhtml/web/js/integrationType.js
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-118
| **What?**         | Fixes max size change and remove extra lines on Admin
| **Why?**          | Because these problems were identified after this PR was merged (#14)
| **How?**          | Fixing javascript code
=> Fixes max size change and remove extra lines on Admin

Model/PagarmeConfigProvider.php, Observer/DataValidateAdmin.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-118
| **What?**         | Disable Enable card wallet and Antifraud at PSP and change error message
| **Why?**          | Because these problems were identified after this PR was merged (#15)
| **How?**          | Adds methods to disable fields
=> Disable the Enable card wallet and Antifraud fields for PSP

Api/HubCommandInterface.php, Block/Adminhtml/Form/Field/HubIntegration.php, Controller/Adminhtml/Hub/Index.php, Model/Api/HubCommand.php, etc/di.xml, etc/webapi.xml, view/adminhtml/web/js/hubIntegration.js
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-144
| **What?**         | Adds hub uninstall feature.
| **Why?**          | To able customers to change the store integrated with hub.
| **How?**          | Defining an url callback on hub end integration that will be called when users exclude the installation at hub.
Add additional informations like screenshots, issue link, etc
* Add pull request labels.
* Check base branch.
* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
=> Adds hub uninstall callback

Api/BulkApiInterface.php, Api/BulkSingleResponseInterface.php, Api/ChargeApiInterface.php, Factories/BulkSingleResponseFactory.php, Model/Api/Bulk.php, Model/Api/BulkSingleResponse.php, Model/Api/Charge.php, Model/Api/ResponseMessage.php, etc/di.xml, etc/webapi.xml
| **What?**         | This PR brings new routes for Magento API that were implemented in the mundipagg repository.
NOTE:
PRs made in the mundipagg repository:
https://github.com/mundipagg/magento2/pull/328
https://github.com/mundipagg/magento2/pull/329
https://github.com/mundipagg/magento2/pull/331
https://github.com/mundipagg/magento2/pull/332
https://github.com/mundipagg/magento2/pull/333
=> Changes from mundipagg repo

Setup/UpgradeSchema.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-179
| **What?**         | Adds table for Hub's token on upgrade
| **Why?**          | To create the "hub_install_token" table in versions older than "1.1.0"
=> [Feature] Adds table for Hub's token on upgrade

Block/Adminhtml/Form/Field/HubEnvironment.php, Concrete/Magento2CoreSetup.php, Controller/Adminhtml/Hub/Index.php, Model/Api/HubCommand.php, etc/adminhtml/system/global.xml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-165 and https://mundipagg.atlassian.net/browse/PAOP-167 
| **What?**         | Adds Hub environment info and removes unused configs
| **Why?**          | To show the Hub's environment integrated and keep configs clean
| **How?**          | Saving the type returned by Hub's API
=> [Feature] Adds Hub environment info

.circleci/data/Dockerfile
| **What?**         | Changes CI image to Magento2.3 on Dockerfile;
| **How?**          | Changing the image in the dockerfile briefly
=> Changes CI image to Magento 2.3

Concrete/Magento2CoreSetup.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-194
| **What?**         | Fixes URL API config on multi-store
| **Why?**          | To allow call the API correctly
| **How?**          | Setting API URL on configuration loading function
=> Fixes load URL in multistore 

etc/adminhtml/system.xml, etc/adminhtml/system/marketplace.xml, i18n/en_US.csv, i18n/pt_BR.csv
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-234
| **What?**         | Adds marketplace config option
| **Why?**          | To allow payment with split at marketplace mode
=> [Feature] Adds marketplace config

Concrete/Magento2PlatformOrderDecorator.php, Gateway/Transaction/Base/Command/InitializeCommand.php, Helper/Marketplace/WebkulHelper.php, Setup/InstallSchema.php, i18n/en_US.csv, i18n/pt_BR.csv, view/adminhtml/templates/marketplace/recipients/create.phtml, view/adminhtml/ui_component/pagarme_pagarme_recipients_listing.xml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-251
| **What?**         | Integration with Webkul module
| **Why?**          | To allow payment with split
| **How?**          | Creating a WebkulHelp class
=> Webkul integration

.circleci/config.yml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-265
| **What?**         | Fix remove ecommerce-module-core to be installed dev version
| **Why?**          | The CI was broken
| **How?**          | Change directory to run composer remove command
=> Fix package remove in ci

Helper/Marketplace/WebkulHelper.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-273
| **What?**         | Development of split remainder logic
| **Why?**          | To allow payment with split
=> Adds split remainder logic

Helper/Marketplace/WebkulHelper.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-273
| **What?**         | Fixes the calculation of the marketplaceCommission to calculate the remainder correctly
=> Fixes the calculation of the marketplaceCommission

Setup/MigrateData.php
| **Issue**         | https://mundipagg.atlassian.net/browse/MC-{ISSUE-NUMBER}
| **What?**         | Replaced Zend log package to Monolog
| **Why?**          | The old package was abandonaded
=> :bug: Replaced Zend-Log to Monolog

.circleci/config.yml, .circleci/data/Dockerfile
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-433
| **What?**         | Adds Webkul Marketplace module in our CI process in order to have it in our staging environment
| **Why?**          | To be able to test all features that dependents on the webkul module
| **How?**          | Changing the main image to magento 2.3.4 and adding webkul marketplace instalation.
**Important Notes**
- We found an issue related to mageto's simple product module and we decided to remove it from the build. So every build that goes to staging after this changes will not create test products by default, we need to create some test products calling magento's webapi latter
=> Adds Webkul Marketplace module in CI deploy to staging 

Helper/ProductHelper.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-434
| **What?**         | implement changes to recurrence order description.
| **Why?**          | To fix a wrong value that was being displaying on recurrence products with discounts applied.
=> :bug: added string verification at product helper

Plugin/Princing/Render/FinalPricePlugin.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-434
| **What?**         | implement changes to recurrence order price.
| **Why?**          | To fix a wrong value that was being displaying on recurrence products with discounts applied.
=> :bug: added discount amount according product interval count

Block/Adminhtml/Marketplace/Recipient.php, Controller/Adminhtml/Recipients/Create.php, view/adminhtml/templates/marketplace/recipients/create.phtml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-278
| **What?**         | List Webkull sellers in create recipient view
=> ✨ List webkull sellers in recipient create view

Model/Notifications.php, Model/PagarmeConfigProvider.php, Plugin/Framework/Webapi/ServicePayloadConverterInterface.php
| **What?**         | Remove object prototyping.
| **Why?**          | Ensure compatibility with other PHP versions
=> :rotating_light: remove strict types

Helper/ProductHelper.php, Observer/DiscountCyclesObserver.php
| **Issue**         | https://mundipagg.atlassian.net/browse/MC-{ISSUE-NUMBER}
| **What?**         | Recurrence price missing the cents.
| **Why?**          | Fix the displayed price.
| **How?**          | Fixed float conversion with comma or dot.
=> PAOPN-12 Cents missing in the recurrence price

etc/di.xml
Questions | Answers
-- | --
Issue | https://mundipagg.atlassian.net/browse/MC-{ISSUE-NUMBER}
What? | Refactor MigreteData.php
Why? | Conflict with Adobe Cloud
How? | Change file folder. Refactor the file within Magento specs.
=> Feature/refactor migrate data/paopn 72

Concrete/Magento2CoreSetup.php
sync saveCardsVoucher with develop ecommerce-module-core
=> :bug: sync saveCardsVoucher with develop ecommerce-module-core

view/adminhtml/web/js/recipients.js
Automatic document type recognition
=> :sparkles: Automatic document type recognition

Block/Payment/Billet.php, Block/Payment/Info/Billet.php, Block/Payment/Info/BilletCreditCard.php, Block/Payment/Info/Pix.php, Block/Payment/Pix.php, Observer/CreditCardDataAssignObserver.php, Observer/DebitDataAssignObserver.php, composer.json
| **Issue**         |[ https://mundipagg.atlassian.net/browse/MC-{ISSUE-NUMBER}](https://mundipagg.atlassian.net/browse/PAOPN-249)
| **What?**         |  Check variable before apply substr method
| **Why?**          |  Method does not support null variable
| **How?**          | Check variable before apply substr method
=> :bug: check variable before substr

Concrete/Magento2CoreSetup.php, Model/PagarmeConfigProvider.php
| **Issue**         | https://mundipagg.atlassian.net/browse/MC-PAOPN-250
| **What?**         | Handle unfilled parameters in settings
| **Why?**          | Error
| **How?**          | Returning empty string if null
=> :bug: fix null parameters in settings

Model/PagarmeConfigProvider.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-254
| **What?**         | make the correct character count.
| **Why?**          | character count is considering characters with accent as 2 characters, it should count as 1
| **How?**          | I changed the method used to count characters from 'strlen' to 'mb_strlen'
=> count_soft_description

Observer/AdminCustomerBeforeSave.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-273
| **What?**         | Error when creating/editing customer data through the administrative portal.
| **Why?**          | Why do you need this implementation/fix?
| **How?**          | Check if the customer already exists at Pagar.Me, if it already exists, perform the validation ignoring the 'document' field if it is blank, if it does not exist, do not validate the customer data with Pagar.Me
=> Bugfix/paopn 273/error when editing customer in adm portal

.circleci/data/Dockerfile, composer.json
=> Update release for PHP 8

Helper/ProductHelper.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-320
| **What?**         | Fix product with downloadable option does not appear in cart
| **Why?**          | Fix product with downloadable option does not appear in cart
| **How?**          | If $title receives an array, turns it into a string
=> PAOPN-320: product with downloadable option does not appear in cart

Concrete/Magento2CoreSetup.php, Model/ConfigNotification.php, etc/adminhtml/system/transaction/creditcard/installments.xml, i18n/pt_BR.csv
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-302
| **What?**         | Handle problem when user fills 0 in "Number of interest-free installments" field
| **Why?**          | The problem would not allow correction via UI
| **How?**          | Prevents the user from entering a value of 0 or less in the "Number of interest-free installments" field and, if changed via the database, launches an alert message
=> PAOPN-302: Error when number of interest free installments 0

Helper/Marketplace/Traits/SplitExtrasAndDiscountsRuleTrait.php, Helper/Marketplace/WebkulHelper.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-325
| **What?**         | fix rule to divide remainder
| **Why?**          | The split rule was not working correctly.
| **How?**          | Removing the percentage multiplication intval and adding another call to handleRemainder
=> PAOPN-325: fix rule to divide remainder

Concrete/Magento2PlatformCustomerDecorator.php, Observer/AdminCustomerBeforeSave.php, Plugin/Admin/CustomerPlugin.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-349
| **What?**         | Add telephone on customer update.
| **Why?**          | If the admin updated the customer's registration, the API was updated and removed the customer's phone, generating a problem in the generation of charges in the recurrence
| **How?**          | Populating the phone field with the phone number present in the Billing and Shipping address
=> PAOPN-349: add telephone on customer update

etc/db_schema.xml, etc/db_schema_whitelist.json
=> :bug: add type in table save cards

Helper/ProductHelper.php
Force value type on convertDecimalMoney function return
=> :bug: force float in convertDecimalMoney value

Concrete/Magento2PlatformOrderDecorator.php, README.md, composer.json, etc/module.xml
- Bug fix: Document value handler for customers #181
=> Bug fix: Document value handler for customers

etc/di.xml
| **Issue**         | https://mundipagg.atlassian.net/browse/MC-{ISSUE-NUMBER}
| **What?**         | Describe in an objective way what has been done.
| **Why?**          | Why do you need this implementation/fix?
| **How?**          | How did you solve the problem? What are the main flows? Any technical information regarding infrastructure or architecture?
Add additional informations like screenshots, issue link, etc
* Add pull request labels.
* Check base branch.
* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
=> :bug: in solve conflict

Block/Product/View/Price/Recurrence.php, Controller/Customer/Cards.php, Service/Client/Api.php, Service/Config/AbstractSystem.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-513
| **What?**         | Removing properties typification.
| **Why?**          | PHP version compatibility
| **How?**          | Removing properties typification.
=> PAOPN-513: Removing properties typification

Block/Customer/Invoice.php, Helper/NumberFormatHelper.php, i18n/en_US.csv, i18n/pt_BR.csv, view/frontend/templates/customer/invoice.phtml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-463
| **What?**         | Refactoring Invoice block and template.
| **Why?**          | Follow best practices.
| **How?**          | Removing business rule code from phtml.
=> PAOPN-463: Refactoring Invoice block and template

Block/Payment/Info/BilletCreditCard.php, Helper/NumberFormatHelper.php, view/frontend/templates/info/billetCreditCard.phtml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-459
| **What?**         | Refactoring BilletCreditCard block and template.
| **Why?**          | Follow best practices.
| **How?**          | Removing business rule code from phtml.
=> PAOPN-459: Refactoring BilletCreditCard block and template

Block/Payment/Info/CreditCard.php, Block/Payment/Info/TwoCreditCard.php, view/frontend/templates/info/twoCreditCard.phtml
| **Issue**           | [https://mundipagg.atlassian.net/browse/PAOPN-461](https://mundipagg.atlassian.net/browse/PAOPN-461)
| **What?**         | Refactored the template and it's associated class.
| **Why?**          | To improve readability and maintainability.
| **How?**          | Extracting some logic into separate private methods
=> Refactoring twoCreditCard info class and phtml

Block/Payment/Info/Billet.php, view/frontend/templates/info/billet.phtml
| **Issue**           | [https://mundipagg.atlassian.net/browse/PAOPN-453](https://mundipagg.atlassian.net/browse/PAOPN-453)
| **What?**         | Refactored the template and it's associated class.
| **Why?**          | To improve readability and maintainability.
| **How?**          | Extracting some logic into separate private methods
=> Refactoring billet info class and phtml

Observer/CreditCardDataAssignObserver.php
| **Issue**           | [https://mundipagg.atlassian.net/browse/PAOPN-450](https://mundipagg.atlassian.net/browse/PAOPN-450)
| **What?**         | Improve Oberver's code
| **Who?**          | @michelpl ([PR #66](https://github.com/pagarme/magento2/pull/66))
=> Improve observers code

view/frontend/web/css/pagarme_style.css, view/frontend/web/template/payment/boleto-form.html, view/frontend/web/template/payment/creditcard-form.html, view/frontend/web/template/payment/multibuyer-form.html, view/frontend/web/template/payment/pix-form.html
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-561
| **What?**         | Removing inline css.
| **Why?**          | Centralize css in css files.
| **How?**          | Moving inline css to css files.
=> refactor: moving inline css to css file

composer.json
| **What?**         | Changing module core version.
| **Why?**          | Changing module core version.
| **How?**          | Changing module core version.
=> build: changing module core version

Setup/UpgradeData.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-548
| **What?**         | Removing string extraction from recurrence.
| **Why?**          | Conflict with other options that use parentheses.
| **How?**          | Removing string extraction from recurrence.
=> fix: changing to use emulateAreaCode

Model/PagarmeConfigProvider.php, Observer/CartAddProductAfterObserver.php, Observer/PaymentMethodAvailable.php, Observer/UpdateProductPlanObserver.php, Plugin/Cart/CartConflict.php, Plugin/CatalogWidget/Block/Product/ProductsList.php, Plugin/Sales/AdminOrder/Product/Quote/Initializer.php, etc/adminhtml/di.xml, etc/di.xml, view/frontend/layout/catalog_product_view.xml, view/frontend/layout/customer_account.xml, view/frontend/layout/pagarme_customer_invoice.xml, view/frontend/layout/pagarme_customer_subscription.xml, view/frontend/layout/pagarme_pagarme_product_list.xml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-574
| **What?**         | Validation for enabled recurrence config to recurrences features.
| **Why?**          | Not call unnecessary code.
| **How?**          | Validation for enabled recurrence config to recurrences features.
=> feat: adding enabled recurrence config validation to recurrences features

Observer/PaymentMethodAvailable.php, Plugin/Cart/CartConflict.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-574
| **What?**         | Validation for enabled recurrence config to recurrences features.
| **Why?**          | Not call unnecessary code.
| **How?**          | Validation for enabled recurrence config to recurrences features.
=> fix: adding pagarmeConfig property

view/adminhtml/web/js/recurrence.js
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-599
| **What?**         | Fixing recurrence price mask.
| **Why?**          | To show the values correctly.
| **How?**          | Fixing the number regex.
=> fix: recurrence price mask showing NaN for all values

view/frontend/web/js/core/checkout/PaymentModuleBootstrap.js
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-540
| **What?**         | Fixing card holder name error message display.
| **Why?**          | Work card holder name error message display.
| **How?**          | Using magento messageList
=> fix: changing to use messageList from magento

Model/InstallmentsByBrandAndAmountManagement.php, Model/InstallmentsByBrandManagement.php, view/adminhtml/templates/info/billetCreditCard.phtml, view/frontend/templates/info/twoCreditCard.phtml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-540
| **What?**         | Fixing strlen on null value for php 8.2
| **Why?**          | Be compatible with php 8.2
| **How?**          | Using empty function before call strlen
=> fix: strlen on null value for php 8.2

Setup/UpgradeSchema.php, composer.json, etc/module.xml
| **What?**         | Fixing module version to be equal with release.
| **Why?**          | 
| **How?**          | Fixing module version to be equal with release.
=> fix: release number version

etc/adminhtml/menu.xml, etc/adminhtml/system/recurrence.xml
…
| **What?**         | adding subscriptions to sales menu and re-adding enabled gateway dependency to show recurrence settings.
| **Why?**          | adding subscriptions to sales menu and re-adding enabled gateway dependency to show recurrence settings
| **How?**          | adding subscriptions to sales menu and re-adding enabled gateway dependency to show recurrence settings
=> feat: adding subscriptions to sales menu and re-adding enabled gateway dependency to show recurrence settings

view/frontend/web/js/core/checkout/PaymentMethodController.js, view/frontend/web/js/core/checkout/PlatformFormHandler.js
| **What?**         | only update installments for valid brands
| **Why?**          | only update installments for valid brands
| **How?**          | only update installments for valid brands
=> fix: change to only update installments for valid brands

Concrete/Magento2PlatformOrderDecorator.php, etc/adminhtml/system/transaction/billet.xml
This reverts commit abf930889a97ecbd3ae35eb23b4bb5fb2b413153.
=> Revert "fix: adding due_at, bank and instructions information to be send to createOrder for billet payment method"

composer.json
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-641
| **What?**         | Update module core with not empty shipping validation.
| **Why?**          | Correct validation shipping code.
| **How?**          | Update module core with develop tag
=> chore: add develop tag to module core

Concrete/Magento2PlatformOrderDecorator.php, Gateway/Transaction/Base/Command/InitializeCommand.php, Service/Transaction/ThreeDSService.php, i18n/pt_BR.csv
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-638
| **What?**         | Sending authentication node to 3ds order.
| **Why?**          | To create order with 3ds authentication in pagar.me
| **How?**          | Sending authentication node inside card node to createOrder request.
=> feat: sending authentication node to 3ds order

Model/TdsToken.php, Service/Transaction/TdsTokenService.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-649
| **What?**         | Changing environment to get tds token deppending on account type.
| **Why?**          | To call the correct get td token endpoint.
| **How?**          | Changing environment to get tds token deppending on account type.
=> feat: changing environment to get tds token deppending on account type

view/adminhtml/web/js/recipients.js
> [!IMPORTANT]
* Corrigido alternação de máscara no campo do número de documento quando `document_type` é `corporation`.
Não foi possível efetuar testes, pois o erro não ocorre no meu ambiente local. Mas foi testado diretamente em stg, efetuando a mesma alteração.
=> fix: document number mask

e2e/helper/pagarme_helper.js, e2e/tests/cartao-de-credito.e2e.test.js, view/frontend/web/js/core/checkout/PaymentMethodController.js, view/frontend/web/js/core/validators/CreditCardValidator.js
> [!IMPORTANT]
* Corrigido validação dos campos de data de validade dos meios de pagamento de cartões
Efetuado testes nas validações dos campos de catão de crédito, débito, voucher e multimeios. Tanto no evento de `change` dos campos, quanto no clique do botão de finalizar pedido.
=> fix: card expiry validation

etc/config.xml
> [!IMPORTANT]
* Alterado os meios de pagamento para serem desabilitados por padrão
Removi as configurações do banco de dados e os meios de pagamentos foram desabilitados
=> fix: payment methods disabled by default

Concrete/Magento2PlatformOrderDecorator.php
> [!IMPORTANT]
Mapeamento do status failed para cancel no pedido do magento
* Recebimento do webhook de charge.payment_failed
=> feat: map failed status to cancel status for magento order

Setup/UpgradeSchema.php, view/adminhtml/web/css/pagarme_style.css, view/adminhtml/web/js/grid/columns/recipientStatus.js
> [!IMPORTANT]
* Adicionado status `refused` ao recebedor
* Status exibido corretamente na lista de recebedores
=> Add kyc status refused

Model/Api/Recipient.php, i18n/pt_BR.csv, view/adminhtml/web/css/pagarme_style.css, view/adminhtml/web/js/grid/columns/recipientStatus.js, view/frontend/templates/customer/marketplace/kyc.phtml, view/frontend/web/css/pagarme_kyc.css
> [!IMPORTANT]
* Alterando mensagens de Marketplace
* Cadastro de recebedor
=> chore: update marketplace messages

Test/Unit/Gateway/Transaction/GooglePay/Config/ConfigTest.php
> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **stg**.
Implementação de testes unitários para configurações do google pay.
Implementação de testes unitários para configurações do google pay.
=> tests: add config tests

Concrete/Magento2CoreSetup.php, composer.json
> [!IMPORTANT]
* Alterado versão do ecommerce-module-core
* Corrigido loop infinito
=> fix: core develop

Concrete/Magento2PlatformOrderDecorator.php, composer.json
> [!IMPORTANT]
Envia os dados de endereço para popular o nó de $card->billing_address para transações de GooglePay
Pedidos em googlepay logados e deslogados
=> fix: passing address to googlepay request

Concrete/Magento2PlatformOrderDecorator.php, Model/Ui/Base/GenericInstallmentsConfigProvider.php, view/frontend/web/js/view/payment/googlepay.js
> [!IMPORTANT]
Removendo duplicidade de código e código não utilizado.
Ida ao checkout.
=> fix: remove duplicate code
