etc/csp_whitelist.xml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-159
| **What?**         | Adds mundipagg domain to csp whitelist.
| **Why?**          | Because our domain was being restricted by Content Security Policies.
| **How?**          | Adding our domain to a csp_whitelist.xml file.
**Important Note**
The domains were added in a csp_whitelist.xml file based on the Magento documentation:
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/security/content-security-policies.html#add-a-domain-to-the-whitelist
=> Adds mundipagg domain to csp whitelist

.circleci/config.yml, Makefile, sonar-project.properties
Essa implementação procura configurar o sonar no projeto _magento2_ e torná-lo parte da pipeline do CircleCi.
O Sonar é uma ferramenta que permite medir como está a qualidade do código em desenvolvimento, e isso é feito medindo o coverage, falhas de segurança, linhas duplicadas, etc.
O sonar foi configurado na URL https://sonarcloud.io/dashboard?id=magento2 e necessita de abertura de ticket no amigo para poder ter acesso.
- Incluído job _Sonar_ e adicionado como etapa obrigatória da execução do _Build_.
- Incluído job _check_quality_gate_sonar_ para validar se o quality gate definido está sendo respeitado em novos PRs. Se gate não for respeitado irá quebrar a pipeline. Essa etapa não é etapa obrigatório do build e não executa nas branches long live (master e develop)
Para ver mais sobre …
=> ci: include sonar and check quality gate

.circleci/data/Dockerfile, Controller/Adminhtml/Charges/Cancel.php, Controller/Adminhtml/Charges/Capture.php, Controller/Adminhtml/Charges/ChargeAction.php, Controller/Adminhtml/Hub/Index.php, Model/Api/HubCommand.php, view/frontend/web/js/core/checkout/PlatformFormBiding.js, view/frontend/web/js/core/checkout/PlatformFormHandler.js
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-194
| **What?**         | Fixes an issue capturing charges after multistore hub integration, gets the correct store id to install/uninstall a hub integration and only uses brands allowed by module in checkout.
| **Why?**          | To allow the customer to use module correctly with the hub integration.
| **How?**          | Setting the correct store id before capturing/canceling charges and before install/uninstall hub integration. Using only brands that exists in module array.
**Important Notes:**
- This PR also returns Magento 2 version in CI to 2.2.
=> Fixes charge capture in multistore

Controller/Adminhtml/Hub/Index.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-167
| **What?**         | Removes public and secret keys (for test and production envs) only if all magento websites are integrated
| **Why?**          | To remove unused fields from database
| **How?**          |  Checking if all other websites are already integrated when finishing a website integration. In this case, we exclude the fields.
=> Removes default config if all websites are integrated to hub

Controller/Adminhtml/Plans/Create.php, Controller/Adminhtml/Plans/Delete.php, Controller/Adminhtml/Plans/Index.php, Controller/Adminhtml/Plans/PlanAction.php, Controller/Adminhtml/Plans/SearchProduct.php, Model/Api/ProductsPlan.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-210
| **What?**         | Fixes plan handling (creation, editing and deletion)
| **Why?**          | To allow users to create plans from bundle products
| **How?**          | Changing core's bootstrap position
**Important Notes**
- Was added a  plan action that holds a bootstrap function that forces configuration loading for **default store**.
- Plans also needs permissions to plan item handling, so i've added it, as obrigatory, in magento2 product in hub: https://hub.pagar.me/apps/magento-2/
=> Fixes plan handling

etc/adminhtml/system/transaction/creditcard/installments/amex.xml, etc/adminhtml/system/transaction/creditcard/installments/aura.xml, etc/adminhtml/system/transaction/creditcard/installments/banese.xml, etc/adminhtml/system/transaction/creditcard/installments/cabal.xml, etc/adminhtml/system/transaction/creditcard/installments/credz.xml, etc/adminhtml/system/transaction/creditcard/installments/diners.xml, etc/adminhtml/system/transaction/creditcard/installments/discover.xml, etc/adminhtml/system/transaction/creditcard/installments/elo.xml, etc/adminhtml/system/transaction/creditcard/installments/hipercard.xml, etc/adminhtml/system/transaction/creditcard/installments/jcb.xml, etc/adminhtml/system/transaction/creditcard/installments/mastercard.xml, etc/adminhtml/system/transaction/creditcard/installments/visa.xml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-213
| **What?**         | Hide and display fields correctly.
| **Why?**          | Because the settings are different for PSP and Gateway clients.
| **How?**          | Adding magento depends tag.
• Before change
• After changes
=> Display admin fields correctly

.circleci/config.yml, .circleci/data/Dockerfile
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-265
| **What?**         | Send to staging ecommerce module core in developer branch
| **Why?**          | To mantain the magento 2 staging with the ecommerce-module-core in developer version
=> Send to staging ecommerce module core on developer branch

etc/adminhtml/system/marketplace.xml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-465
| **What?**         | Shows marketplace option only when advanced settings is enabled.
| **Why?**          | Because only Gateway customers will use it.
| **How?**          | Verifying if advanced settings is enabled before showing marketplace fields.
When "advanced settings" is disabled:
When "advanced settings" is enabled:
=> Hides marketplace option

view/frontend/templates/payment/pix.phtml
| **Issue**           | https://mundipagg.atlassian.net/browse/PAOPN-261
| **What?**         | Exchanged the method `document.execCommand`, witch is deprecated, with `navigator.clipboard.writeText`
| **Why?**          | The method was not working on Safari in IOS and Mac.
| **How?**          | By replacing the method, the function would work only on secure connections. So, as an alternative, if this method fails, it tries the `document.execCommand` as before, and with that failing, it allows the user to copy the code manually.
=> PAOPN-261 Bug fix on the function copyQrCode that was not working on Apple browsers

Model/PagarmeConfigProvider.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-262
| **What?**         | make the correct character count.
| **Why?**          | character count is considering characters with accent as 2 characters, it should count as 1
| **How?**          | I changed the method used to count characters from 'strlen' to 'mb_strlen' and from 'substr' to 'mb_substr'
=> PAOPN-262: replacement of strlen and substr methods in softdescription

view/frontend/web/js/core/checkout/PaymentMethodController.js
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-284
| **What?**         | Order summary resets the total amount when selecting one of the multi-means payment methods.
| **Why?**          | To view the total amount of the order on the screen after changing the payment method
| **How?**          | Removed '.selector' function which is deprecated in jQuery 3.
=> PAOPN-284: removed '.selector' function which is deprecated in jQuery 3

view/frontend/web/js/core/checkout/PaymentMethodController.js
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-286
| **What?**         | Remove .selector 
| **Why?**          | .selector is deprecated in 1.7 and removed in version 3
| **How?**          | Remove .selector 
* [JQuery Documentation](https://api.jquery.com/selector/)
=> Remove .selector because it's removed from JQuery3

Observer/PaymentMethodAvailable.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-285
| **What?**         | Bug fix of not displaying payment methods at checkout when using recurring products
| **Why?**          | Fix needed to display payment methods when recurring product
| **How?**          | Remove array_flip because it is not needed and in version 8+ it generates a problem.
=> remove array_flip because it is not necessary

Block/Payment/Info/Billet.php, Block/Payment/Info/BilletCreditCard.php, Block/Payment/Info/CreditCard.php, Block/Payment/Info/Pix.php, Block/Payment/Info/TwoCreditCard.php, view/adminhtml/templates/info/billetCreditCard.phtml, view/frontend/web/js/core/checkout/PaymentMethodController.js
| **Issue**         | [https://mundipagg.atlassian.net/browse/PAOPN-291](https://mundipagg.atlassian.net/browse/PAOPN-291)
| **What?**         | Checked if charge and transaction existis before using them
| **Why?**          | Admin Order View had error if these informations were removed from the database
| **How?**          | Returning empty array if $orderObject is null
=> Bugfix/paopn 291/error visualizing order in admin

etc/csp_whitelist.xml
| **Issue**           | [https://mundipagg.atlassian.net/browse/PAOPN-295](https://mundipagg.atlassian.net/browse/PAOPN-295)
| **What?**         | Fixed PIX QRCode not showing on the store.
| **Why?**          | PIX QRCode was being blocked by CSP policy.
| **How?**          | Added _https://api.pagar.me_ to CSP Whitelist.
=> PAOPN-295 PIX QRCode image was blocked by CSP

etc/csp_whitelist.xml
| **Issue**           | [https://mundipagg.atlassian.net/browse/PAOPN-294](https://mundipagg.atlassian.net/browse/PAOPN-294)
| **What?**         | Fixed PIX QRCode not showing on the store.
| **Why?**          | PIX QRCode was being blocked by CSP policy.
| **How?**          | Added _https://api.pagar.me_ to CSP Whitelist
=> PAOPN-294 PIX QRCode image was blocked by CSP

Block/Payment/Info/Billet.php, Block/Payment/Info/BilletCreditCard.php, Block/Payment/Info/CreditCard.php, Block/Payment/Info/Pix.php, Block/Payment/Info/TwoCreditCard.php, view/adminhtml/templates/info/billetCreditCard.phtml
| **Issue**           | [https://mundipagg.atlassian.net/browse/PAOPN-292](https://mundipagg.atlassian.net/browse/PAOPN-292)
| **What?**         | Checked if charge and transaction existis before using them
| **Why?**          | Admin Order View had error if these informations were removed from the database
| **How?**          | Returning empty array if $orderObject is null
=> Bugfix/paopn 292/error visualizing order in admin

view/adminhtml/templates/recurrence/subscriptions/details.phtml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-258
| **What?**         | Fix bugs in subscription details
| **Why?**          | Fix bugs in subscription details
| **How?**          | Remove ->getValue and assign it empty to $cancelUrl if no billet link
=> PAOPN-258: fix error accessing subscription details

Helper/Marketplace/Traits/SplitExtrasAndDiscountsRuleTrait.php, Helper/Marketplace/WebkulHelper.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-325
| **What?**         | fix rule to divide remainder
| **Why?**          | The split rule was not working correctly.
| **How?**          | Add the comparison with empty and 0, because the empty() function considers 0 to be empty.
=> Fix split rule

Block/Adminhtml/Recurrence/Subscriptions/Subscription.php, Concrete/Magento2CoreSetup.php, Concrete/Magento2DataService.php, Concrete/Magento2PlatformOrderDecorator.php, Concrete/Magento2PlatformPaymentMethodDecorator.php, Controller/Adminhtml/Charges/Cancel.php, Controller/Adminhtml/Charges/Capture.php, Controller/Adminhtml/Hub/Index.php, Controller/Adminhtml/Plans/SearchProduct.php, Controller/Customer/Remove.php, Gateway/Transaction/Base/ResourceGateway/AbstractRequestDataProvider.php, Helper/Adminhtml/CheckoutHelper.php, Helper/BuildChargeAddtionalInformationHelper.php, Helper/ModuleHelper.php, Helper/ProductHelper.php, Model/Api/ProductsSubscription.php, Model/Api/Recipient.php, Model/CardsRepository.php, Model/InstallmentsByBrandAndAmountManagement.php, Model/Maintenance.php, Model/Payment.php, Plugin/Framework/Webapi/ServicePayloadConverterInterface.php, Ui/Component/Column/Actions.php
| **Issue**           | https://mundipagg.atlassian.net/browse/PAOPN-355
| **What?**         | Fixed deprecated "Passing null to parameter" on functions in PHP8
| **Why?**          | To avoid exceptions ion this situations
| **How?**          | By adding `?? ''` to functions that expect strings
=> Fixing deprecated "Passing null to parameter"

Block/Adminhtml/System/Config/Form/Field/MarketplaceMessage.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-521
| **What?**         | Compatibilization with magento 2.3.x.
| **Why?**          | Breaking setup:di:compile in magento 2.3.x versions
| **How?**          | Using usual php multiline string concatenation
=> PAOPN-521: Compatibilization with magento 2.3.x

Block/Payment/Info/CreditCard.php, view/frontend/templates/info/creditCard.phtml
| **Issue**           | [https://mundipagg.atlassian.net/browse/PAOPN-454](https://mundipagg.atlassian.net/browse/PAOPN-454)
| **What?**         | Refactored the template and it's associated class.
| **Why?**          | To improve readability and maintainability.
| **How?**          | Extracting some logic into separate private methods
=> Feature/paopn 454/refactoring credit card phtml template

Block/Payment/Info/TwoCreditCard.php, Concrete/Magento2DatabaseDecorator.php, Console/Command/MigrateExecute.php, Console/Command/MigrateList.php, Console/MigrateData.php, Controller/Adminhtml/Charges/Cancel.php, Controller/Adminhtml/Charges/Capture.php, Controller/Adminhtml/Charges/ChargeAction.php, Controller/Adminhtml/Plans/PlanAction.php, Controller/Adminhtml/Recipients/RecipientAction.php, Controller/Adminhtml/RecurrenceProducts/Delete.php, Helper/CustomerUpdatePagarmeHelper.php, Helper/Marketplace/WebkulHelper.php, Helper/ProductSubscriptionHelper.php, Model/Api/HubCommand.php, Model/Api/ProductsSubscription.php, Model/Api/Subscription.php, Model/Cart/CartConflict.php, Model/InstallmentsByBrandAndAmountManagement.php, Model/InstallmentsByBrandManagement.php, Model/Ui/Base/GenericInstallmentsConfigProvider.php, Observer/SalesOrderPlaceAfter.php, Plugin/CatalogWidget/Block/Product/ProductsList.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-393
| **What?**         | Compatibilization with magento 2.4.6 and PHP 8.2.
| **Why?**          | Work with more versions.
| **How?**          | Adding properties definition to compatibilize with PHP 8.2.
=> feat: compatibilization with magento 2.4.6 and PHP 8.2

Model/Graphql/PixDataProvider.php, Plugin/GraphQl/PlaceOrder.php, etc/graphql/di.xml, etc/schema.graphqls
| **Issue**           | [https://mundipagg.atlassian.net/browse/PAOPN-450](https://mundipagg.atlassian.net/browse/PAOPN-450)
| **What?**         | Added pix information to GraphQL
| **Why?**          | My system use graphql and we need this informations
| **How?**          | We only added this informations to graphql
| **Who?**          | @ianitsky ([PR #70](https://github.com/pagarme/magento2/pull/70))
Input:
```
placeOrder(input: {
cart_id: $cart_id
}) {
order {
order_number
}
pagarme_pix {
qr_code
qr_code_url
}
}
```
Output:
```
"placeOrder": {
"order": {
"order_number": "3000000085"
},
"pagarme_pix": {
"qr_code": "https://digital.mundipagg.com/pix/",
"qr_code_url": …
```
=> Added pix informations to graphql

Gateway/Transaction/Base/Command/InitializeCommand.php, Model/Api/ProductsPlan.php, Model/WebhookManagement.php, Observer/OrderCancelAfter.php
| Questions     | Answers 
| **Issue**         | [https://github.com/pagarme/magento2/issues/237](https://github.com/pagarme/magento2/issues/237) 
| **What?**         | Updated the httpCode argument when throwing a new Magento\Framework\Webapi\Exception.
| **Why?**          | Magento\Framework\Webapi\Exception constructor throws an Exception if httpCode is not between 400 and 599
| **How?**          | Passing a httpCode, expected from Webapi\Exception, instead of 0, or any other number that comes from a caught exception. `} catch (\Exception $e) {` for example, does not guarantee that  $e->getCode() is going to return a number between 400 and 599.
Magento\Framework\Webapi\Exception constructor
* Add pull request …
=> Fix Webapi\Exception __construct arguments

Concrete/Magento2PlatformOrderDecorator.php, etc/adminhtml/system/transaction/billet.xml
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-608
| **What?**         | Adding due_at, bank and instructions information to be send to createOrder for billet payment method.
| **Why?**          | Send correct information to create billet order.
| **How?**          | Adding due_at, bank and instructions information to be send to createOrder for billet payment method.
=> fix: adding due_at, bank and instructions information to be send to createOrder for billet payment method

Gateway/Transaction/CreditCard/Config/Config.php, Gateway/Transaction/CreditCard/Config/ConfigInterface.php, Model/Ui/CreditCard/ConfigProvider.php, etc/adminhtml/system/transaction/creditcard/tds.xml, etc/config.xml, i18n/pt_BR.csv, view/frontend/web/js/core/models/CreditCardModel.js
| **Issue**           | https://mundipagg.atlassian.net/browse/PAOPN-666
| **What?**         | Added min value to 3DS.
=> feat: added min value to 3ds

Block/Payment/Billet.php, Block/Payment/Pix.php, Gateway/Transaction/Base/Command/InitializeCommand.php, Helper/Payment/Billet.php, Helper/Payment/Pix.php
> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **stg**.
Adicionado método alternativo para buscar as informações de QrCode de Pix ou URL de Boleto. Ver tarefa: https://mundipagg.atlassian.net/browse/PAOPN-663
Defini `null` no `$orderId` para testar o retorno da nova função quando a original falhar. Retorno está conforme esperado. Testado pedidos com Pix, Boleto e Cartão de Crédito. Todos ok!
=> feat: alternate pix and billet info

Model/Notifications.php
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOPN-682
| **What?**         | Fix sintax error for setup:di:compile on magento 2.3.0
| **Why?**          | Be compatible with magento 2.3.0
| **How?**          | Remove sintax error
| **Issue**           | https://github.com/pagarme/magento2/issues/309
=> fix: sintax error for di compile

Controller/Adminhtml/Recipients/Create.php, i18n/pt_BR.csv, view/adminhtml/templates/marketplace/recipients/create.phtml, view/adminhtml/web/js/recipients.js
> [!IMPORTANT]
* Corrigido alternação de maxLength no campo do número de documento quando `document_type` é `corporation`.
* Corrigido título da página de recebedores quando entra para visualizar.
Não foi possível efetuar testes, pois o erro não ocorre no meu ambiente local. Mas o recurso de `maxLengh` não é necessário já que o campo possui máscara, o que já limita o seu tamanho.
=> fix: recipient document maxLength

Model/WebhookManagement.php, Test/Unit/Model/WebhookManagementTest.php
Adição da validação de webhook de recipient.
Teste de webhooks com os status do [épico](https://mundipagg.atlassian.net/browse/PA-933).
=> feat: added recipient webhook validation

etc/adminhtml/system/transaction/googlepay.xml, i18n/pt_BR.csv
> [!IMPORTANT]
* Adicionado campo nas opções de Google Pay para inserção do Account ID da Pagar.me quando a loja não foi recentemente integrada.
* Corrigido os campos das configurações de Google Pay para exibi-los apenas quando o Google Pay estiver ativo
* Campo adicionado salvando account id no mesmo registro da integração do Hub.
=> Paopn 755/feat add account id to gpay

Gateway/Transaction/GooglePay/Config/Config.php
| **Issue**         | #356 
| **What?**         | Handle empty card brand configuration.
| **Why?**          | So the checkout page can work as expected with credit card payment disabled.
| **How?**          | Handling the null return from the database, when there is no credit card configured.
=> handle empty card brands configuration

Api/RecipientInterface.php
| **Issue**         | #358 
| **What?**         | Fix return method annotation
| **Why?**          | To swagger work as expected
| **How?**          | Add the full path to KycLinkResponseInterface at the return definition at the method `createKycLink`
=> update return type in RecipientInterface createKycLink method

view/frontend/web/js/core/checkout/PaymentMethodController.js, view/frontend/web/js/core/checkout/Tds.js, view/frontend/web/js/core/models/CreditCardModel.js, view/frontend/web/js/view/payment/default.js, view/frontend/web/js/view/payment/googlepay.js
> [!IMPORTANT]
Corrige valor incorreto no checkout.
O valor agora passa a considerar taxas e impostos pré-configurados pelo admin.
Pedidos em todos os meios de pagamento.
=> PLATS-25: checkout value does not include taxes

Api/SubscriptionApiInterface.php, Model/Api/Subscription.php, Test/Unit/Model/Api/SubscriptionTest.php
> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **stg**.
Foi alterado para que só crie o SubscriptionService quando estiver apenas no escopo de WebAPi Rest, fazendo com que os comando queue:consumers:start funcione sem estar integrado no Hub.
Rodado o comando abaixo com sucesso:
`bin/magento queue:consumers:start async.operations.all -vvv`
=> fix: queue commands running without Pagar.me integration

Block/Payment/Info/BaseCardInfo.php, Controller/Adminhtml/Invoices/Delete.php, Controller/Adminhtml/Plans/Delete.php, Controller/Adminhtml/Subscriptions/Delete.php, view/frontend/templates/info/card.phtml
> [!IMPORTANT]
Correção de bugs na tradução e a referência do bloco no HTML.
Testes de tradução e do bloco.
=> fix: translations calls and blocks blocks references

Gateway/Transaction/Base/Command/InitializeCommand.php
> [!IMPORTANT]
> Certifique-se de criar o PR para a branch **stg**.
Método `createOrderAtPagarme` foi modificado no [Core](https://github.com/pagarme/ecommerce-module-core/pull/177) e agora retorna um objeto, no lugar de um array contendo apenas um objeto. Essa função é utilizada no Magento uma única vez. Este PR refatora para tratar a resposta como objeto.
Testado fluxos de compras com Cartão de Crédito, Pix e Boleto
[ECPJ-54]: https://allstone.atlassian.net/browse/ECPJ-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: createOrderAtPagarme returns object
